### ISSUE TITLE
What can i do to run as admin

### ISSUE THREAD

**Issue by tuanvayn** [hustoj/hustoj-neo#6]
I assigned a account like a admin and how to make a problem or contest. many thanks

**Comment by zhblue** [comment]
assigned admin to gain administrator privilege works only on my fork
https://github.com/zhblue/hustoj
if you are working with this fork , you need to use sql
```
insert into privilege values('admin','adminsitrator','N');
```
to get the same thing

**Comment by freefcw** [comment]
run command:

`php artisan assign:admin`

will ask you some question about your admin account

**Comment by tuanvayn** [comment]
@freefcw I have runned assign command and success. but which route to navigate to management page?

**Comment by tuanvayn** [comment]
@zhblue can your folk run on window?

**Comment by tuanvayn** [comment]
Nothing to show...
![image](https://user-images.githubusercontent.com/22125166/39419173-d84dc550-4c88-11e8-8e96-8c5dc7c3ef57.png)

**Comment by zhblue** [comment]
web always works on windows ,while the judged and judge_client  don't without VM

**Comment by tuanvayn** [comment]
owner. I need your help

**Comment by freefcw** [comment]
@tuancongtuyn 

Sorry, I have ill for some days 

You should run 

```
npm run prod
npm run admin-prod
```

`npm run prod ` will generate front resources
`npm run admin-prod` will generate admin resrouces

please try this

**Comment by tuanvayn** [comment]
@freefcw many thanks for ur supporting. I'll try

**Comment by zhblue** [comment]
> @zhblue can your folk run on window?
a package for windows available now
https://github.com/Azure99/WinHustOJ/releases
